project:
  type: website
  output-dir: docs
  
website:
  title: "Brian Paul Boyle"
  navbar:
 # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd
     # - text: "Blogs"
     #   href: blogs/index.qmd
      - text: "Data Visualisation"
        href: datavis/index.qmd

format:
  html:
    theme: 
    - lumen
    - custom.scss
    css: styles.css
    toc: true
    fontsize: 1.1em

editor: visual

