---
title: "Online election campaigning in changing political environments: A comparison of the 2014 and 2019 European Parliament elections"
date: 2025-02-07
author:
  - name: Sebastian Stier
    orcid: 0000-0002-1217-5778
    affiliation: University of Mannheim
  - name: Yannis Theocharis
    orcid: 0000-0001-7209-9669
    affiliation: Technical University of Munich
  - name: Sebastian Adrian Popa
    orcid: 0000-0002-7133-7255
    affiliation: Newcastle University   
  - name: Brian Paul Boyle
    orcid: 0000-0003-1996-5104
    affiliation: Newcastle University
categories: 
    - European Parliament
    - Election campaigns
    - Social media
    - Text as data
pub-info:
  links:
    - name: Final version
      url: https://journals.sagepub.com/doi/full/10.1177/13540688251317855
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/13540688251317855
      icon: ai ai-zotero
doi: 10.1177/13540688251317855
---

## Abstract

It has long been assumed that social media would equalize election campaigning by providing cheap means of communication for smaller parties who lack a strong mass media presence. Yet given the increased political importance of social media, parties with more professional staff and resources could also gain the upper hand in online campaigns. So far, knowledge of the development of online campaigning in a rapidly changing political landscape remains limited, as only few studies have taken a longitudinal and cross-country approach so far. This paper conducts a comprehensive analysis of more than 12,000 unique candidates from all 28 European Union (EU) member states in the 2014 and 2019 European Parliament (EP) elections. We theorize and empirically assess how party size, the populist nature of parties and their EU position relate to the presence and activity of EP candidates on Twitter as well as the salience of the EU in their tweets. The results show that candidates of parties with a bigger national vote share were more likely to have a Twitter account and tweet more on the EU. Overall, the findings point to a normalization of online election campaigning over time and a further convergence of first and second-order elections.

## Citation

Stier, S. et al. (2025) 'Online election campaigning in changing political environments: A comparison of the 2014 and 2019 European Parliament elections', Party Politics, Available at: https://doi.org/10.1177/13540688251317855.

<p class="buttons" style="text-align:center;">

<a class="btn btn-danger btn-sm" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1177/13540688251317855">Add to Zotero </a>

</p>
