---
title: "Territorial variance in the UK’s refugee politics and its consequences: Young Syrian refugees in England and Scotland"
date: 2023-03-29
author:
  - name: Gareth Mulvey
    orcid: 0000-0002-9132-1672
    affiliation: University of Glasgow
  - name:  Dimitris Skleparis
    orcid: 0000-0002-6302-1277
    affiliation: Newcastle University
  - name: Brian Paul Boyle
    orcid: 0000-0003-1996-5104
    affiliation: Newcastle University
categories: 
  - Migration
  - Refugee settlement
  - Social policy
  - UK
pub-info:
  links:
    - name: Final version
      url: https://journals.sagepub.com/doi/10.1177/2399654423116544
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/2399654423116544
      icon: ai ai-zotero
doi: 10.1177/2399654423116544
---

## Abstract

Access to social rights is crucial to refugee settlement and integration, and a whole range of social policy measures determine the limits on those rights. In the United Kingdom (UK) various relevant social policies are divided into devolved and reserved categories. This has resulted in a distinct territorial variance in social rights and welfare provisions within the country. The aim of this article is to explore how young Syrian refugees experience this territorial divergence in two jurisdictions: in Scotland, where they are part social citizens; and in England, where access to social rights is more limited. We use the prism of social citizenship as a means of examining the experiences of settlement and integration of Syrian refugees in the two nations. We draw out contrasts between these experiences and locate them within the interactions between the politics of welfare and refugee politics in the two nations. We argue that fine variances in England\'s and Scotland\'s social rights and welfare regimes have an impact on the settlement experiences of refugees. England\'s less supportive regime fosters self-reliance and faster labour market integration among refugees. However, this environment pushes refugees in England to accept any job that they might find, no matter how precarious, or how far it may be from their educational qualifications, past professional experience or aspirations. This has overarching implications for refugees\' outlook on life and long-term planning.

## Citation

Mulvey, G., Skleparis, D., & Boyle, B. (2023). Territorial variance in the UK’s refugee politics and its consequences: Young Syrian refugees in England and Scotland. Environment and Planning C: Politics and Space, 41(5), 958-975. https://doi.org/10.1177/23996544231165440

<p class="buttons" style="text-align:center;">

<a class="btn btn-danger btn-sm" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1177/2399654423116544"> Add to Zotero </a>

</p>

``` bibtex
@article{doi:10.1177/23996544231165440,
author = {Gareth Mulvey and Dimitris Skleparis and Brian Boyle},
title ={Territorial variance in the UK’s refugee politics and its consequences: Young Syrian refugees in England and Scotland},
journal = {Environment and Planning C: Politics and Space},
volume = {41},
number = {5},
pages = {958-975},
year = {2023},
doi = {10.1177/23996544231165440},
URL = {https://doi.org/10.1177/23996544231165440},
eprint = {https://doi.org/10.1177/23996544231165440}
```
