---
title: "Engineering Democracy: Electoral Rules and Turnout Inequality"
date: 2022-06-07
author:
  - name: Brian Paul Boyle
    url: https://brianpaulboyle.com/
    orcid: 0000-0003-1996-5104
    affiliation: Newcastle University
categories: 
  - Compulsory Voting
  - Turnout Inequality
  - Electoral Rules
  - Survey Data
pub-info:

  links:

    - name: Final version
      url: https://journals.sagepub.com/doi/10.1177/00323217221096563
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/00323217221096563
      icon: ai ai-zotero
doi: 10.1177/00323217221096563
---

## Abstract

The issue of unequal electoral turnout poses serious concerns for both the overall health of democratic politics, and the extent to which certain groups exert an unequal influence on the political process. This article explores the relationship between electoral rules such as: compulsory voting, electoral system proportionality, and voter registration with voter inequality in terms of age, income and education. This is examined using cross-national survey data and cross-level interactions between electoral institutions and socio-demographic variables. The final dataset is based on waves 2--4 of the Comparative Study of Electoral Systems, and contains information on 133,000 individuals, within 45 countries, between 2001 and 2016. The results indicate that compulsory voting is associated with a significant reduction in turnout inequalities, while the effects of proportionality and voter registration are somewhat more mixed.

## Citation

Boyle, B. P. (2024). Engineering Democracy: Electoral Rules and Turnout Inequality. Political Studies, 72(1), 177-199. https://doi.org/10.1177/00323217221096563

<p class="buttons" style="text-align:center;">

<a class="btn btn-danger btn-sm" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1177/00323217221096563">Add to Zotero </a>

</p>

``` bibtex
@article{doi:10.1177/00323217221096563,
author = {Brian Paul Boyle},
title ={Engineering Democracy: Electoral Rules and Turnout Inequality},
journal = {Political Studies},
volume = {72},
number = {1},
pages = {177-199},
year = {2024},
doi = {10.1177/00323217221096563},
URL = {https://doi.org/10.1177/00323217221096563},
eprint = {https://doi.org/10.1177/00323217221096563}}
```
